import { type PackageInfo } from './shared';


export function generateNixFlake(packages: PackageInfo[]): string {
    const attrs = packages.map(p => p.pkg);

    return `# Experimental Nix Flake — generated by ParchMate
# Install: nix profile install
# or:      sudo nixos-rebuild switch --flake .# (NixOS)

{
  description = "System packages from ParchMate selection";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { nixpkgs, ... }: let
    forAllSystems = nixpkgs.lib.genAttrs nixpkgs.lib.platforms.linux;
  in {
    packages = forAllSystems (system: {
      default = nixpkgs.legacyPackages.\${system}.buildEnv {
        name = "tuxmate-packages";
        paths = [
${attrs.map(a => `          nixpkgs.legacyPackages.\${system}.${a}`).join('\n')}
        ];
      };
    });
  };
}
`;
}

export function generateNixProfileCommand(packages: PackageInfo[]): string {
    const attrs = packages.map(p => `nixpkgs#${p.pkg}`);
    return `nix profile install ${attrs.join(' ')}`;
}
